model:
  name: basic_catboost_reg
  test_size: 0.2
  params:
    loss_function: RMSE
    custom_metric: [MAE, MAPE, MedianAbsoluteError, R2]
    depth: 8
    random_seed: 42
    silent: True

common:
  data: california_housing
  raw_data_path: ./data/raw_datasets/
  processed_data_path: ./data/processed/
  is_mlflow_logging: False
  mlflow_uri: http://127.0.0.1:5000
