model:
  name: basic_catboost_reg
  test_size: 0.2
  #  inference_model: mlflow_models/basic_catboost_reg
  onnx_model_name: onnx_catboost
  onnx_model_path: /nvidia-triton/model_repository/onnx_catboost/1/model.onnx
  params:
    loss_function: RMSE
    custom_metric: [MAE, MAPE, MedianAbsoluteError, R2]
    depth: 8
    random_seed: 42
    silent: True

common:
  data: california_housing
  raw_data_path: ./data/raw_datasets/
  processed_data_path: ./data/processed/
  is_mlflow_logging: False
  mlflow_uri: http://127.0.0.1:5000
  mlflow_models_path: ./mlflow_models/
  triton_path: ./nvidia_triton/
  deviation_threshold: 1e-3
