name: pre-commit

on:
  push:
  pull_request:

jobs:
  pre-commit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mlops_tools repo
        uses: actions/checkout@v3
      - name: Install Python3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Set up pre-commit
        uses: pre-commit/action@v3.0.0
